name: base-app-3

services:
  app:
    image: ${BASE_APP_IMAGE:-base-app-3:local}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./backend/.env
    volumes:
      - app_storage:/var/www/html/storage
    restart: unless-stopped

volumes:
  app_storage:
