<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Municipality;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    /**
     * Municipalities of El Salvador grouped by department code (cod_dpto).
     * Source: División Política Administrativa de El Salvador.
     *
     * @var array<string, array<int, string>>
     */
    private array $municipalities = [
        '01' => [
            'Ahuachapán',
            'Apaneca',
            'Atiquizaya',
            'Concepción de Ataco',
            'El Refugio',
            'Guaymango',
            'Jujutla',
            'San Francisco Menéndez',
            'San Lorenzo',
            'San Pedro Puxtla',
            'Tacuba',
            'Turín',
        ],
        '02' => [
            'Santa Ana',
            'Candelaria de la Frontera',
            'Chalchuapa',
            'Coatepeque',
            'El Congo',
            'El Porvenir',
            'Masahuat',
            'Metapán',
            'San Antonio Pajonal',
            'San Sebastián Salitrillo',
            'Santa Rosa Guachipilín',
            'Santiago de la Frontera',
            'Texistepeque',
        ],
        '03' => [
            'Sonsonate',
            'Acajutla',
            'Armenia',
            'Caluco',
            'Cuisnahuat',
            'Izalco',
            'Juayúa',
            'Nahuizalco',
            'Nahulingo',
            'Salcoatitán',
            'San Antonio del Monte',
            'San Julián',
            'Santa Catarina Masahuat',
            'Santa Isabel Ishuatán',
            'Santo Domingo de Guzmán',
            'Sonzacate',
        ],
        '04' => [
            'Chalatenango',
            'Agua Caliente',
            'Arcatao',
            'Azacualpa',
            'Cancasque',
            'Citalá',
            'Comalapa',
            'Concepción Quezaltepeque',
            'Dulce Nombre de María',
            'El Carrizal',
            'El Paraíso',
            'La Laguna',
            'La Palma',
            'La Reina',
            'Las Vueltas',
            'Nombre de Jesús',
            'Nueva Concepción',
            'Nueva Trinidad',
            'Ojos de Agua',
            'Potonico',
            'San Antonio de la Cruz',
            'San Antonio Los Ranchos',
            'San Fernando',
            'San Francisco Lempa',
            'San Francisco Morazán',
            'San Ignacio',
            'San Isidro Labrador',
            'San José Cancasque',
            'San José Las Flores',
            'San Luis del Carmen',
            'San Miguel de Mercedes',
            'San Rafael',
            'Santa Rita',
            'Tejutla',
        ],
        '05' => [
            'Santa Tecla',
            'Antiguo Cuscatlán',
            'Ciudad Arce',
            'Colón',
            'Comasagua',
            'Chiltiupán',
            'Huizúcar',
            'Jayaque',
            'Jicalapa',
            'La Libertad',
            'Nuevo Cuscatlán',
            'Quezaltepeque',
            'Sacacoyo',
            'San José Villanueva',
            'San Juan Opico',
            'San Matías',
            'San Pablo Tacachico',
            'Talnique',
            'Tamanique',
            'Teotepeque',
            'Tepecoyo',
            'Zaragoza',
        ],
        '06' => [
            'San Salvador',
            'Aguilares',
            'Apopa',
            'Ayutuxtepeque',
            'Cuscatancingo',
            'Ciudad Delgado',
            'El Paisnal',
            'Guazapa',
            'Ilopango',
            'Mejicanos',
            'Nejapa',
            'Panchimalco',
            'Rosario de Mora',
            'San Marcos',
            'Soyapango',
            'Santo Tomás',
            'Santiago Texacuangos',
            'Tonacatepeque',
        ],
        '07' => [
            'Cojutepeque',
            'Candelaria',
            'El Carmen',
            'El Rosario',
            'Monte San Juan',
            'Oratorio de Concepción',
            'San Bartolomé Perulapía',
            'San Cristóbal',
            'San José Guayabal',
            'San Pedro Perulapán',
            'San Rafael Cedros',
            'San Ramón',
            'Santa Cruz Analquito',
            'Santa Cruz Michapa',
            'Suchitoto',
            'Tenancingo',
        ],
        '08' => [
            'Zacatecoluca',
            'Cuyultitán',
            'El Rosario',
            'Jerusalén',
            'Mercedes La Ceiba',
            'Olocuilta',
            'Paraíso de Osorio',
            'San Antonio Masahuat',
            'San Emigdio',
            'San Francisco Chinameca',
            'San Juan Nonualco',
            'San Juan Talpa',
            'San Luis La Herradura',
            'San Luis Talpa',
            'San Miguel Tepezontes',
            'San Pedro Masahuat',
            'San Pedro Nonualco',
            'San Rafael Obrajuelo',
            'Santa María Ostuma',
            'Santiago Nonualco',
            'Tapalhuaca',
        ],
        '09' => [
            'Sensuntepeque',
            'Cinquera',
            'Dolores',
            'Guacotecti',
            'Ilobasco',
            'Jutiapa',
            'San Isidro',
            'Tejutepeque',
            'Victoria',
        ],
        '10' => [
            'San Vicente',
            'Apastepeque',
            'Guadalupe',
            'San Cayetano Istepeque',
            'San Esteban Catarina',
            'San Ildefonso',
            'San Lorenzo',
            'San Sebastián',
            'Santa Clara',
            'Santo Domingo',
            'Tecoluca',
            'Tepetitán',
            'Verapaz',
        ],
        '11' => [
            'Usulután',
            'Alegría',
            'Berlín',
            'California',
            'Concepción Batres',
            'El Triunfo',
            'Ereguayquín',
            'Estanzuelas',
            'Jiquilisco',
            'Jucuapa',
            'Jucuarán',
            'Mercedes Umaña',
            'Nueva Granada',
            'Ozatlán',
            'Puerto El Triunfo',
            'San Agustín',
            'San Buenaventura',
            'San Dionisio',
            'San Francisco Javier',
            'Santa Elena',
            'San Jorge',
            'San Juan del Río',
            'Tecapán',
        ],
        '12' => [
            'San Miguel',
            'Carolina',
            'Chapeltique',
            'Chinameca',
            'Chirilagua',
            'Ciudad Barrios',
            'Comacarán',
            'El Tránsito',
            'Lolotique',
            'Moncagua',
            'Nueva Guadalupe',
            'Nuevo Edén de San Juan',
            'Quelepa',
            'San Antonio',
            'San Gerardo',
            'San Jorge',
            'San Luis de la Reina',
            'San Rafael Oriente',
            'Sesori',
            'Uluazapa',
        ],
        '13' => [
            'San Francisco Gotera',
            'Arambala',
            'Cacaopera',
            'Chilanga',
            'Corinto',
            'Delicias de Concepción',
            'El Divisadero',
            'El Rosario',
            'Gualococti',
            'Guatajiagua',
            'Joateca',
            'Jocoaitique',
            'Lolotiquillo',
            'Meanguera',
            'Osicala',
            'Perquín',
            'San Carlos',
            'San Fernando',
            'San Isidro',
            'San Simón',
            'Sensembra',
            'Sociedad',
            'Torola',
            'Yamabal',
            'Yoloaiquín',
        ],
        '14' => [
            'La Unión',
            'Anamorós',
            'Bolívar',
            'Concepción de Oriente',
            'Conchagua',
            'El Carmen',
            'El Sauce',
            'Intipucá',
            'Lislique',
            'Meanguera del Golfo',
            'Nueva Esparta',
            'Pasaquina',
            'Polorós',
            'San Alejo',
            'San José',
            'Santa Rosa de Lima',
            'Yayantique',
            'Yucuaiquín',
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $departments = Department::all()->keyBy('cod_dpto');

        foreach ($this->municipalities as $codDpto => $names) {
            $department = $departments->get($codDpto);
            if (! $department) {
                continue;
            }

            foreach ($names as $name) {
                Municipality::withTrashed()->updateOrCreate(
                    [
                        'name' => $name,
                        'department_id' => $department->id,
                    ],
                    ['deleted_at' => null]
                );
            }
        }
    }
}
